# Generated by Django 5.0.6 on 2024-06-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='tag',
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ManyToManyField(related_name='scopes', to='articles.article'),
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ManyToManyField(to='articles.tag'),
        ),
    ]
