# Generated by Django 5.0.6 on 2024-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_scope_article_remove_scope_tag_scope_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='tag',
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.tag'),
            preserve_default=False,
        ),
    ]
