# Generated by Django 5.0.6 on 2024-06-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_scope_article_remove_scope_tag_scope_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.scope'),
            preserve_default=False,
        ),
    ]
