# Generated by Django 5.0.6 on 2024-07-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='names',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='articles.article', verbose_name='Статья'),
        ),
    ]
