# Generated by Django 5.0.6 on 2024-06-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teachers_remove_student_teacher_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
