# Generated by Django 5.0.6 on 2024-06-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_teachers_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
