# Generated by Django 5.0.6 on 2024-06-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='prise',
            new_name='price',
        ),
    ]
