name: django test homework

on:
  push:
    branches: [video]
  workflow_dispatch:


jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Проверяем репозиторий на наличие изменений
      uses: actions/checkout@v3
      with:
        path: Jango_project_home/3.2-crud/workflows/project.yml

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Установка зависемостей
      run: pip install -r 3.2-crud/stocks_products/requirements.txt

    - name: Линтинг кода
      run: flake8 stocks_products --exclude migrations --ignore E501
